# Generated by Django 5.0.1 on 2024-02-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handyapp', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact',
            field=models.CharField(default='', max_length=15),
        ),
    ]
